eris_store/eris_store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eris_store/main/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.auth import views as auth_views
from .filter_laptop import FilterLaptopView
from .views import (
    AllView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    CreateAccountView,
    CategoryFilterLaptopsView,
    SearchViews,
    TestSearchProductView,
    AddStarRatingView,
    SendCommentViews,
    VerificationView,
    RandomProductERMAView,
    RandomView

)

urlpatterns = [
    path('', AllView.as_view(), name='all'),
    path('search-product-test/', TestSearchProductView.as_view(), name='search_product_test'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('filter-laptop/', FilterLaptopView.as_view(), name='filter_laptop'),
    path('filter-laptop-category/', CategoryFilterLaptopsView.as_view(), name='filter_laptop_category'),
    path('search/', SearchViews.as_view(), name='search_all'),
    path('products/<slug>/', views.product_rating, name='base_product'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-gty-cart/<str:slug>/', ChangeQTYView.as_view(), name='change_gty_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('account/', views.account_view, name='account'),
    path('change_information/', views.change_information_view, name='change_information'),
    path('change_icon/', views.change_icon_view, name='change_icon'),
    path('change_sequence/', views.change_sequence_view, name='change_sequence'),
    path('add-rating/', views.AddStarRatingView.as_view(), name='add_rating'),
    path('post-comment/', views.post_comment, name="post_comment"),
    path('products/<slug>/comment/', views.leave_comment_and_rating_views, name="leave_comment_rating"),
    path('send-comment/', SendCommentViews.as_view(), name="send_comment"),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate'),
    path('random-product/', RandomView.as_view(), name='random_product'),
    path('random-product-erma/', RandomProductERMAView.as_view(), name='random_product_erma'),
    path('promo-code/', views.promo_cod_view, name='promo_code'),


    path('accounts/password_reset/',
         PasswordResetView.as_view(template_name='main/reset_password/password_reset_form.html'),
         name='password_reset'),
    path('accounts/password_change/done/',
         PasswordResetDoneView.as_view(template_name='main/reset_password/password_reset_done.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='main/reset_password/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         PasswordResetCompleteView.as_view(template_name='main/reset_password/password_reset_complete.html'),
         name='password_reset_complete'),
]

eris_store/main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import date, datetime, timezone
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.db.models import Count, Avg


User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


class Category(models.Model):
    name = models.CharField(verbose_name='Name category', max_length=250)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Brand(models.Model):

    name = models.CharField(verbose_name='Brand', max_length=250)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):

#       --------------------------------  all ------------------------------------------------        #

    category = models.ForeignKey("Category", verbose_name='Category', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, verbose_name='Brand', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Name', max_length=250)
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Imagine')
    description = models.TextField(verbose_name='description', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Price')
    total_rating = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Rating Star product')

#         ---------------------------------------------- laptop ------------------------           #

    by_series = models.ForeignKey('BySeriesLaptop', verbose_name='By series laptop',
                                  on_delete=models.CASCADE, null=True, blank=True)
    operating_system = models.ForeignKey('OperatingSystemLaptop', verbose_name='Operating system laptop'
                                         , on_delete=models.CASCADE, null=True, blank=True)
    screen_size = models.CharField(max_length=255, verbose_name='Screen size', blank=True)
    resolution = models.CharField(max_length=255, verbose_name='Resolution', null=False, blank=True)
    graphics = models.ForeignKey('VideoLaptop', verbose_name='Graphics', null=True, on_delete=models.CASCADE,
                                 blank=True)
    processor = models.ForeignKey('CPULaptop', verbose_name='CPU laptop', null=True, on_delete=models.CASCADE,
                                  blank=True)
    cpu_speed = models.CharField(max_length=255, verbose_name='CPU Speed', blank=True)
    cpu_core = models.CharField(max_length=255, verbose_name='CPU Core', blank=True)
    ram = models.ForeignKey('RAM', verbose_name='Memory(RAM)', null=True, on_delete=models.CASCADE, blank=True)
    storage_drive_size = models.CharField(max_length=255, verbose_name='Storage drive size', blank=True)
    touch = models.BooleanField(default=True, verbose_name='Touch/Non Touch')
    battery_charge = models.CharField(max_length=255, verbose_name='Battery life', blank=True)
    #         ---------------------------------------------- smartphone ------------------------           #
    operating_system_smartphone = models.ForeignKey('OperatingSystemSmartphone',
                                                    related_name='Operating System Smartphone+'
                                                    , on_delete=models.CASCADE, null=True, blank=True)
    diagonal = models.CharField(max_length=255, verbose_name='Diagonal', null=False, blank=True)
    resolution_smartphone = models.CharField(max_length=255, verbose_name='Resolution', null=False, blank=True)
    camera = models.CharField(max_length=255, verbose_name='Camera', null=False, blank=True)
    type_screen = models.CharField(max_length=255, verbose_name='Type screen', null=False, blank=True)
    processor_smartphone = models.ForeignKey('CPUSmartphone', verbose_name='CPU Smartphone', on_delete=models.CASCADE
                                             , null=True, blank=True)
    ram_smartphone = models.ForeignKey('RAM', verbose_name='RAM(smartphone)', related_name='RAM for smartphone+',
                                       on_delete=models.CASCADE, null=True, blank=True)
    battery_charge_smartphone = models.CharField(max_length=255, verbose_name='Battery charge', null=False, blank=True)
    sd = models.BooleanField(default=True, verbose_name='SD', null=False, blank=True)
    sd_volume_max = models.CharField(
        max_length=255, null=False, blank=True, verbose_name='Sd volume max'
    )
    #         ---------------------------------------------- headphone ------------------------           #
    color = models.CharField(max_length=255, verbose_name='Color', blank=True)
    fit_type = models.CharField(max_length=255, verbose_name='Fit type', blank=True)
    item_dimensions = models.CharField(max_length=255, verbose_name='Item dimensions', blank=True)
    item_weight = models.CharField(max_length=255, verbose_name='Item weight', blank=True)
    battery = models.CharField(max_length=255, verbose_name='Batteries', blank=True)

    def __str__(self):
        return "{} : {}.".format(self.category.name, self.title)

    def get_absolute_url(self):
        return reverse('base_product', kwargs={'slug': self.slug})

    def get_model_name(self):
        return self.__class__.__name__.lower()


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Customer', on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey('Cart', verbose_name='Cart', on_delete=models.CASCADE, related_name='related_products')
    product = models.ForeignKey(Product, verbose_name='Name product', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Total Price')

    def __str__(self):
        return "Product: {} (for Cart)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.total_price = self.qty * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name='Customer', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    total_price = models.DecimalField(max_digits=9, default=0,  decimal_places=2, verbose_name='Total Price')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class CompareProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Customer', on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, verbose_name='Name product', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "Product: {} (for Compare)".format(self.product.title)


class Compare(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Customer', on_delete=models.CASCADE)
    products = models.ManyToManyField(CompareProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Customer', on_delete=models.CASCADE)
    icon = models.ImageField(verbose_name='Icon', default='owner.png', upload_to='icon/')
    sequence = models.ImageField(verbose_name='Sequence', default='sequence.jpg', upload_to='sequence/')
    phone = models.CharField(max_length=20, verbose_name='Phone', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Address', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Buyers orders', related_name='related_customer')
    virtual_money = models.PositiveIntegerField(verbose_name='Virtual money(erma)', default=0, null=True, blank=True)

    def __str__(self):
        return "Customer: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'pickup'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'New order'),
        (STATUS_IN_PROGRESS, 'Order in progress'),
        (STATUS_READY, 'Order is ready'),
        (STATUS_COMPLETED, 'Order completed')
    )
    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Pickup'),
        (BUYING_TYPE_DELIVERY, 'Delivery')
    )

    customer = models.ForeignKey(Customer, verbose_name='Customer', related_name='related_orders',
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Name')
    last_name = models.CharField(max_length=255, verbose_name='Last name')
    phone = models.CharField(max_length=255, verbose_name='Phone')
    cart = models.ForeignKey(Cart, verbose_name='Cart', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Address', null=True, blank=True)
    status = models.CharField(
        max_length=255,
        verbose_name='Status is order',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=255,
        verbose_name='Order type',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Order comment', null=True, blank=True)

eris_store/main/templates/main/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function ($) {
        $('#id_sd').on('click', function () {
            if ($('#id_sd').prop('checked') == true) {
                $('#id_sd_volume_max').prop('readonly', false)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'white')
            } else {
                $('#id_sd_volume_max').prop('readonly', true)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'Lightgray')
            }
        })
    })(django.jQuery);
</script>
{% endblock %}

eris_store/main/templates/main/blog_comment.html
{% load static %}
{% load humanize %}
{% load specifications %}


<link rel="stylesheet" href="{% static '/main/css/blog_comment_style.css' %}" type="text/css"/>
<div class="div-blog-comment">
    <div class="div-blog-two-comment">
        {% if user.is_authenticated %}
        <a href="{% url 'leave_comment_rating' slug=product.slug %}">
        <button id="button-blog-comment-leave-id">LEAVE YOUR COMMENT</button>
            </a>
        {% else %}
        <div class="div-blog-comment-login-to-post">
            <h6 style="color: #ff0; text-shadow: 0 0 5px #ff0;">PLEASE LOGIN TO POST A COMMENT</h6>
        </div>
        {% endif %}
        {% for com in comments_html %}

        <div class="div-blog-comment-whole-comment">
            <div class="div-blog-comment-two-whole-comment">
                <b class="b-blog-comment-username"> {{ com.user.username }} </b>
                <span class="span-blog-comment-timestamp">{{ com.timestamp| naturaltime }}</span>
                <hr style="color: #ff0; margin-top: 7px;">
                <div class="div-blog-comment-comment"> {{ com.comment }}</div>
            </div>
            {% if user.is_authenticated %}
            <button class="button-blog-comment-reply" data-target="#comment{{ com.sno }}" id="button{{ com.sno }}"
                    aria-controls="#comment{{ com.sno }}" aria-expanded="false"
                    data-toggle="collapse"  type="button">REPLY</button>
            {% endif %}

        </div>

        <div class="div-blog-comment-reply">
            <div class="collapse" id="comment{{ com.sno }}">
                <div class="div-blog-comment-two-leave-reply-comment">
                    <form class="form-blog-comment-leave-reply-comment" action="{% url 'post_comment' %}" method="post">
                        {% csrf_token %}
                        <div class="div-blog-comment-form-reply-comment">
                            <input type="text" class="div-blog-comment-reply-comment-text" name="comment" placeholder="Enter comment here"
                                   id="comment">
                            <input type="hidden" name="parentSno" value="{{ com.sno }}">
                        </div>
                        <input type="hidden" name="product_id" value="{{ com.product_comment_id }}">
                        <button type="submit" class="button-blog-comment-reply-comment">Submit</button>
                    </form>
                </div>
            </div>
            <div>
                {% for reply in reply_dict|get_val:com.sno %}
                <div>
                    <div class="div-blog-comment-whole-reply-comment">
                        <div class="div-blog-comment-two-whole-reply-comment">
                            <b class="b-blog-comment-reply-username"> {{ reply.user.username }} </b>
                            <span class="span-blog-comment-reply-timestamp">{{ reply.timestamp| naturaltime }}</span>
                            <hr style="color: #ff0; margin-top: 7px;">
                            <div class="div-blog-comment-reply-comment">{{ reply.comment }}</div>
                        </div>
                        <br>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}



    </div>
</div>

eris_store/main/templates/main/cart.html
{% extends 'main/all.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/main/css/cart_style.css' %}" type="text/css">
<div style="display: flex; justify-content: center; align-items: center;">
  <!--<div class="col-lg-9">-->
  <!--    {% if messages %} {% for message in messages %}-->
  <!--    <div class="alert alert-success alert-dismissible fade show" role="alert">-->
  <!--        <strong>{{ message }}</strong>-->
  <!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
  <!--    </div>-->
  <!--</div>-->

  <!--{% endfor %} {% endif %}-->

  {% if not cart.products.count %}
  <div class="div-cart-empty">
    <div class="div-cart-content-empty">
      <div class="div-cart-two-content-empty">
        <h3 class="h3-cart-empty">Your cart Empty</h3>
      </div>
    </div>
  </div>
  {% endif %}

  <!--{% if messages %}-->
  <!--{% for message in messages %}-->
  <!--<div class="alert alert-success alert-dismissible fade show" role="alert">-->
  <!--  <strong>{{ message }}</strong>-->
  <!--  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
  <!--</div>-->
  <!--{% endfor %}-->
  <!--{% endif %}-->
  {% if cart.products.count %}
  <div class="div-cart-product">
    <div class="div-cart-product-nav">
      <p id="p-cart-col-name" class="p-cart-product-nav">NAME(PRICE)</p>
      <p id="p-cart-col-picture" class="p-cart-product-nav">PICTURE</p>
      <p id="p-cart-col-total-price" class="p-cart-product-nav">TOTAL PRICE</p>
      <p id="p-cart-col-action" class="p-cart-product-nav">ACTION</p>
    </div>
    <table class="table-cart-product">
      <tbody class="tbody-cart-product">

      {% for item in cart.products.all %}


      <tr class="tr-cart-product">

        <th class="th-cart-product-title" scope="row">{{ item.product.title }}
          <p class="p-cart-product-price">{{ item.product.price }}$</p></th>

        <td class="td-cart-product-image"><img src="{{ item.product.image.url }}" class="img-cart-product">
        </td>


        <td class="td-cart-product-qty">
          <form action="{% url 'change_gty_cart' slug=item.product.slug %}"
                method="POST">
            {% csrf_token %}
            <input type="number" class="input-cart-product-qty" name="qty" min="1" value="{{ item.qty }}">
            <br>
            <input type="submit" class="input-cart-product-qty-submit" value="CHANGE QUANTITY">
          </form>
        </td>
        <td class="td-cart-product-total-price"><p class="p-cart-product-total-price">{{ item.total_price }}$</p></td>

        <td class="td-cart-product-delete-from-cart">

          <a href="{% url 'delete_from_cart' slug=item.product.slug %}">
            <button class="button-cart-product-delete-from-cart">DELETE FROM CART</button>
          </a>
        </td>
      </tr>

      {% endfor %}


      <tr>
        <td colspan="2"></td>
        <td class="td-cart-total">Total:</td>
        <td class="td-cart-total-products">{{ cart.total_products }}</td>
        <td class="td-cart-total-price">{{ cart.total_price }} $</td>
        <td><a href="{% url 'checkout' %}">
          <button class="button-cart-checkout">CHECKOUT</button>
        </a></td>
      </tr>
      </tbody>
    </table>
    <!--  <form action="{% url 'promo_code' %}" method="get">-->
    <!--      <input type="text" name="promo_codes" placeholder="Please enter the code">-->
    <!--      <input type="submit" value="Apple">-->
    <!--    </form>-->
    <!--    <p>{{ codes.code }}</p>-->
  </div>
  {% endif %}
</div>



{% endblock %}

eris_store/main/templates/main/checkout.html
{% extends 'main/all.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/main/css/checkout_style.css' %}" type="text/css">
<div style="display: flex; justify-content: center; align-items: center;">
  <div>
    <div>
      <h3 class="h3-checkout-text">ORDER GOODS</h3>
    </div>
    <div class="div-checkout-product">
      <div class="div-checkout-product-nav">
        <p id="p-checkout-col-name" class="p-checkout-product-nav">NAME(PRICE)</p>
        <p id="p-checkout-col-picture" class="p-checkout-product-nav">PICTURE</p>
        <p id="p-checkout-col-number" class="p-checkout-product-nav">NUMBER</p>
        <p id="p-checkout-col-total-price" class="p-checkout-product-nav">TOTAL PRICE</p>
      </div>
      <table class="table-checkout-product">
        <tbody>
        {% for item in cart.products.all %}

        <tr class="tr-checkout-product">

          <th class="th-checkout-product-title" scope="row">{{ item.product.title }}
            <p class="p-checkout-product-price">{{ item.product.price }}$</p></th>

          <td class="td-checkout-product-image"><img src="{{ item.product.image.url }}" class="img-checkout-product">
          </td>
          <td class="td-checkout-qty">{{ item.qty }}</td>
          <td class="td-checkout-product-total-price">
            <p class="p-checkout-product-total-price">{{ item.total_price }}$</p>
          </td>


        </tr>


        {% endfor %}

        <tr>
          <td colspan="2"></td>
          <td class="td-checkout-total">Total:</td>
          <td class="td-checkout-total-products">{{ cart.total_products }}</td>

          <td class="td-checkout-total-price">{{ cart.total_price }} $</td>
        </tr>

        </tbody>
      </table>
    </div>

    <hr>

    <div class="div-checkout-order">
      <div class="div-checkout-order-two">
        <!--    <h3 class="text-canter mt-5 mb-5">Form order</h3>-->
        <form action="{% url 'make_order' %}" method="POST">
          <div class="div-checkout-order-form">
            <div class="div-checkout-order-form-two">
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" class="input-checkout-form" value="Order goods">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

eris_store/main/templates/main/confirm_code_mail.html
<!--{% extends "main/all.html" %}-->
<!--{% load static %}-->

<!--{% block content %}-->
<!--<link rel="stylesheet" href="{% static '/main/css/password_reset_style.css' %}" type="text/css"/>-->
<!--<div class="div-password-reset">-->
<!--    <div class="div-password-reset-two">-->
<!--        <form action="{% url 'conf_code_html' %}" method="post">-->
<!--            <div class="div-password-reset-form">-->
<!--                <h3 style="text-align: center; color: #ff0; text-shadow: 0 0 5px #ff0;">Reset your password</h3>-->
<!--                <hr style="color: #ff0; text-shadow: 0 0 5px #ff0;">-->

<!--                <p class="p-password-reset-text">Please enter your code twice:</p>-->
<!--                <input type="text" name="code">-->
<!--                <input class="input-password-reset" type="submit" value="Confirm">-->

<!--            </div>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->


<!--{% endblock %}-->

eris_store/main/templates/main/create_account.html
{% extends 'main/all.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/main/css/create_account_style.css' %}" type="text/css"/>
<div style="display: flex; justify-content: center; align-items: center;">
    <div class="div-create-account">
        <div class="div-create-account-form">

            <form style="" action="" method="post">
                <div class="div-create-account-two-form">
                    <h3 style="color: #ff0; text-shadow: 0 0 5px #ff0;" class="text-center">Create account</h3>
                    <hr style="color: #ff0; text-shadow: 0 0 5px #ff0;">
                    <div class="div-create-account-three-form">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" class="button-create-account-form" value="Sign in">

                    </div>
                </div>
            </form>


        </div>
    </div>
</div>



{% endblock %}

eris_store/main/templates/main/edit.html
{% extends 'main/all.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
<link rel="stylesheet" href="{% static '/main/css/edit_style.css' %}" type="text/css"/>
<div style="display: flex; justify-content: center; align-items: center;">
    <div class="div-edit">
        <div class="div-edit-form">
            <form method="post" enctype="multipart/form-data">

                <div class="div-edit-two-form">
                    {% csrf_token %}
                    {{ form_information_html|crispy }}
                    {{ form_sequence_html|crispy }}
                    {{ form_icon_html|crispy }}

                    <button class="button-edit-form" type="submit">Save change</button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

eris_store/main/templates/main/leave_comment_and_rating.html
{% extends 'main/all.html' %}
{% load static %}
{% load specifications %}

{% block content %}
{% if user.is_authenticated %}
{% for product in product_html %}
<link rel="stylesheet" href="{% static '/main/css/leave_comment_and_rating_style.css' %}" type="text/css"/>
<div style="display: flex; justify-content: center; align-items: center;">
    <div class="div-leave-comment">
        <div class="div-leave-comment-two">
            <div class="div-leave-comment-form">
                <form name="rating" action="{% url 'add_rating' %}" method="post">
                    <h3 style="color: #ff0; text-shadow: 0 0 5px #ff0; text-align: center;
                font-family: 'Sprite Graffiti', serif;
                position: relative; top: 20px;">LEAVE COMMENT AND ASSESSMENT
                    </h3>
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <b style="color: #ff0; text-shadow: 0 0 5px #000; margin-left: 18px;
                 font-family: 'Sprite Graffiti', serif;">ASSESSMENT:</b>
                    <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>

                </form>

                <form class="form-leave-send-comment" action="{% url 'send_comment' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input class="input-leave-form-text" id="input-leave-form-text-id" type="text" name="comment"
                           placeholder="Enter comment here">

                    <input type="hidden" name="parent_sno" value="">
                    <input class="input-leave-form-submit" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</div>
<script>

    const rating = document.querySelector('form[name=rating]');

    rating.addEventListener("change", function (e) {

        let data = new FormData(this);
        fetch(`${this.action}`, {
            method: 'POST',
            body: data
        })
            .then(response => console.log(response))
            .then(success => console.log(success))
            .catch(error => console.log(error))
    });





</script>
{% endfor %}
{% endif %}

{% endblock %}